let name = "Maksim";
console.log(typeof name);
let age = 22;
console.log(typeof age);
let boolean = false;
console.log(typeof boolean);
let bigNumber = 123314325239239432558n;
console.log(typeof bigNumber);
let none = null;
console.log(typeof none);
let undefinedType = undefined;
console.log(typeof undefinedType);
let symbolString = $;
console.log(typeof symbolString);