const name = "Maksim";
console.log(typeof name);
const age = 22;
console.log(typeof age);
const boolean = false;
console.log(typeof boolean);
const bigNumber = 123314325239239432558n;
console.log(typeof bigNumber);
const none = null;
console.log(typeof none);
const undefinedType = undefined;
console.log(typeof undefinedType);